server:
  port: 8082
  servlet:
    context-path: "/truck-vehicle/"

spring:
  application:
    name: truck-vehicle-service
  datasource:
    url: jdbc:postgresql://localhost:5432/truck-vehicle
    username: postgres
    password: adm123
  jpa:
    hibernate:
      ddl-auto: update #alteracoes em objetos serao refletidos no banco de dados
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.no-contextual-creation: true #bloqueia leitura de meta informacoes que podem gerar log de erro na inicializacao do hibernate
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    com.ead: INFO
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO


management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
